### ISSUE TITLE
Problem with Unicode chars

### ISSUE THREAD

**Issue by saman-ghm** [andryuha49/odata-v4-typeorm#9]
It seems there is a problem with unicode or white-space characters. E.g. when I'm trying to execute following query I'm facing parse error, it seems it's related to `odata-v4-parser`:
`?$count=true&$filter=substringof(firstName,"سامان")`

**Comment by andryuha49** [comment]
Hi, @saman-ghm !
Please give me information about your database and share the error which you have got. 
I will debug it.

**Comment by saman-ghm** [comment]
Hi @andryuha49,
I'm using Sql Server 2017 and the error says:

> Error: Unexpected character at 31
    at D:\node_projects\node_modules\odata-v4-typeorm\node_modules\odata-v4-parser\src\parser.ts:19:39

It seems it's related to `odata-v4-parser` and unicode chars.

**Comment by andryuha49** [comment]
Hi, @saman-ghm!
Does that PL (https://github.com/andryuha49/odata-v4-typeorm/pull/10) solve the unicole issue?

**Comment by saman-ghm** [comment]
Hi @andryuha49,
Yes it does :)

**Comment by andryuha49** [comment]
version 0.0.12 was published

**Comment by andryuha49** [comment]
@saman-ghm thank you!
